### ISSUE TITLE
Redmi Note 6 Pro is duplicated

### ISSUE THREAD

**Issue by PiotrZPL** [crdroidandroid/crdroid.net#10]
Redmi Note 6 Pro is duplicated; it is included as both `tulip` and `twolip`, both on your [download page](https://crdroid.net/downloads), and in the [devices_handler](https://crdroid.net/devices_handler/compiled.json).

According to [this post](https://forum.xda-developers.com/t/tulip-twolip-difference.4063299/), this is the same device, just renamed to avoid conflicts:
> They are both same devices it's just that since in Lineage OS device list, there is already a device with tulip code name some dev named Redmi Note 6 pro (Tulip to Twolip) to avoid confusion. But yes, other ROM that are using different device tree are using original code name Tulip

![On the website](https://user-images.githubusercontent.com/79166768/211161447-44dbbdb9-3719-44c0-aa33-82e3840ec4d8.png)

![In the handler](https://user-images.githubusercontent.com/79166768/211161529-1f76143a-a64b-4745-ac5f-40090e4d0eb9.png)

**Comment by gwolf2u** [comment]
This is by design as you said
Old name is preserved as that's how it was initially
