### ISSUE TITLE
 Crdroid. Product sales

### ISSUE THREAD

**Issue by Pantyhose-X** [crdroidandroid/crdroid.net#12]
Please provide "[USB C THUMB DRIVE 128G](https://www.amazon.com/KOOTION-Samsung-Oneplus-MacBook-Chromebook/dp/B088LMS5VV/?th=1)"+ Crdroid. Product sales
This will change the entire Android ecology

* At present, the device needs to be tested by the CRDroid:
You can install Crdroid on the Bootloader UnLocking device to install Crdroid

* Imagine: In the future, Android devices have no built -in operating system:
By inserting USB C Thumb Drive installation, people can freely choose any OS distribution version,
In the developer mode, users can set the Bootloader UnLocking password,
Restore Factory Settings, Bootloader unlocking passwords will be deleted.

**Comment by gwolf2u** [comment]
sorry but no interest in that
