### ISSUE TITLE
Website lists outdated revisions even when unchecked in Firefox 129

### ISSUE THREAD

**Issue by Lost-Entrepreneur439** [crdroidandroid/crdroid.net#20]
When loading the crDroid website on Firefox 129 on Linux, the website is listing outdated revisions and EOL devices/brands even though it is unchecked, if I check the box then uncheck it then all the outdated revisions go away, but by default it shows them despite being unchecked.

**Comment by gwolf2u** [comment]
I can not confirm this
Try clearing cache

**Comment by Lost-Entrepreneur439** [comment]
Cleared cache and also tried on a separate computer which has never been on crdroid.net before, issue still persists.

**Comment by gwolf2u** [comment]
Having AdBlock on?

**Comment by Lost-Entrepreneur439** [comment]
I did have an adblocker on (uBlock Origin specifically), tried disabling it and it fixed the issue.

**Comment by gwolf2u** [comment]
can you check now please
do clear browser cache

**Comment by Lost-Entrepreneur439** [comment]
Issue is fixed now
