### ISSUE TITLE
Unfriendly spot

### ISSUE THREAD

**Issue by ghost** [crdroidandroid/crdroid.net#9]
Loading this site is so slowly!
As a teenager, in my perspective, it's not very morden.

Some suggests:
 1. Decrease CSS ( I think only need 500 lines )
 2. Decrease Image size ( use webp )
 3. Use Javascript less
 4. Let it hit everyone's spot!

My [site](https://wll.moe) ( Open-source too ) you can view!

**Comment by gwolf2u** [comment]
1.2s for full page load is not bad imo
https://gtmetrix.com/reports/crdroid.net/6ciwSYYn

1. Css is as is as we use bootstrap
2. Only device images are webp and rest of elements are quite small size
3. Js is also with frameworks
